# /// script
# requires-python = "==3.14.*"
# ///
"""Generate conformance/name_fold.json, the shared name fold table (SDK spec §4.4.1).

Run: uv run conformance/tools/gen_fold_table.py           (writes the table)
     uv run conformance/tools/gen_fold_table.py --check   (fails if the committed table differs)

The table is generated from one pinned Unicode version, so every SDK folds
names the same way, whatever Unicode version its runtime ships. The script
refuses to run on a Python whose unicodedata has a different version.

For each code point in the covered blocks:
  1. NFKD,
  2. remove the combining marks,
  3. apply the default lowercase,
  4. map the letters that do not decompose (EXTRA below).
Only code points whose folded string differs from the code point itself are
written. A code point that is not in the table folds to itself.
"""
import argparse
import json
import sys
import unicodedata
from pathlib import Path

UNICODE_VERSION = "16.0.0"

# Inclusive code point ranges, by Unicode block name.
BLOCKS = [
    ("Basic Latin", 0x0000, 0x007F),
    ("Latin-1 Supplement", 0x0080, 0x00FF),
    ("Latin Extended-A", 0x0100, 0x017F),
    ("Latin Extended-B", 0x0180, 0x024F),
    ("Greek and Coptic", 0x0370, 0x03FF),
    ("Cyrillic", 0x0400, 0x04FF),
    ("Latin Extended Additional", 0x1E00, 0x1EFF),
]

# Lowercase letters that NFKD does not decompose to a base letter.
EXTRA = {
    "ø": "o",
    "æ": "ae",
    "œ": "oe",
    "ß": "ss",
    "ł": "l",
    "đ": "d",
    "ð": "d",
    "þ": "th",
    "ı": "i",
}

OUT = Path(__file__).resolve().parent.parent / "name_fold.json"


def fold_char(ch):
    decomposed = unicodedata.normalize("NFKD", ch)
    stripped = "".join(c for c in decomposed if not unicodedata.combining(c))
    lowered = stripped.lower()
    return "".join(EXTRA.get(c, c) for c in lowered)


def build():
    table = {}
    for _, first, last in BLOCKS:
        for cp in range(first, last + 1):
            ch = chr(cp)
            if unicodedata.category(ch) == "Cn":  # unassigned
                continue
            folded = fold_char(ch)
            if folded != ch:
                table[cp] = folded
    # The fold must be stable: folding a folded string again changes nothing.
    for cp, folded in table.items():
        again = "".join(table.get(ord(c), c) for c in folded)
        if again != folded:
            raise SystemExit(f"fold not idempotent at U+{cp:04X}: {folded!r} -> {again!r}")
        if any(unicodedata.combining(c) for c in folded):
            raise SystemExit(f"combining mark left at U+{cp:04X}: {folded!r}")
    return table


def render(table):
    doc = {
        "description": "Shared name fold table for station name search (SDK spec 4.4.1). "
        "Keys are code points (upper-case hex, at least 4 digits); values are the folded strings. "
        "A code point that is not in the map folds to itself. Generated by conformance/tools/gen_fold_table.py; do not edit.",
        "unicode_version": UNICODE_VERSION,
        "steps": ["NFKD", "remove combining marks", "default lowercase", "extra letters"],
        "extra": EXTRA,
        "blocks": [{"name": n, "first": f"{a:04X}", "last": f"{b:04X}"} for n, a, b in BLOCKS],
        "map": {f"{cp:04X}": table[cp] for cp in sorted(table)},
    }
    return json.dumps(doc, ensure_ascii=False, indent=1) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="compare with the committed table; write nothing")
    args = parser.parse_args()

    if unicodedata.unidata_version != UNICODE_VERSION:
        raise SystemExit(
            f"this Python has Unicode {unicodedata.unidata_version}; the table is pinned to {UNICODE_VERSION}. "
            "Run it with uv, which picks the Python version in the script header."
        )
    text = render(build())
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
        if current != text:
            print(f"{OUT} differs from a fresh generation")
            return 1
        print(f"{OUT} matches a fresh generation ({len(json.loads(text)['map'])} entries, Unicode {UNICODE_VERSION})")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(json.loads(text)['map'])} entries, Unicode {UNICODE_VERSION})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
