# /// script
# requires-python = ">=3.10"
# ///
"""Build the single-file amalgamation (SDK spec 6.4):

    uv run c/tools/amalgamate.py [--out c/dist]

writes <out>/opentideconstants.h (the public header) and <out>/opentideconstants.c
(the library, the fold table, the vendored SHA-256 and cJSON, with cJSON and
SHA-256 renamed to otc__*). Copy both files into a project and compile them
with any C99 compiler: cc -std=c99 -c opentideconstants.c (link with -lm, and
-pthread on an old glibc).
"""
import argparse
import re
from pathlib import Path

C = Path(__file__).resolve().parents[1]

# Our sources, then the vendored ones. cJSON.c goes last: it redefines true and false.
PARTS = [
    "src/otc_cjson_rename.h",
    "src/otc_sha256_rename.h",
    "vendor/cjson/cJSON.h",
    "vendor/sha256/sha-256.h",
    "src/otc_internal.h",
    "src/otc_util.c",
    "src/otc_release.c",
    "src/otc_query.c",
    "src/otc_station.c",
    "src/otc_fold_table.c",
    "src/otc_fetch_stub.c",
    "vendor/sha256/sha-256.c",
    "vendor/cjson/cJSON.c",
]
LOCAL_INCLUDE = re.compile(r'^\s*#\s*include\s+"([^"]+)"\s*$')

PRELUDE = """/*
 * opentideconstants.c - single-file amalgamation of the OpenTideConstants C
 * library {version}. Generated by c/tools/amalgamate.py; do not edit.
 *
 * The library is MIT. It contains cJSON {cjson} (MIT, Copyright (c) 2009-2017
 * Dave Gamble and cJSON contributors) and amosnier/sha-2 (Unlicense / 0BSD);
 * see c/vendor/README.md in https://github.com/opentideconstants/sdk.
 */
#if !defined(_WIN32) && !defined(_POSIX_C_SOURCE)
#define _POSIX_C_SOURCE 200809L
#endif
#if defined(_MSC_VER) && !defined(_CRT_SECURE_NO_WARNINGS)
#define _CRT_SECURE_NO_WARNINGS
#endif
#ifndef CJSON_HIDE_SYMBOLS
#define CJSON_HIDE_SYMBOLS
#endif
#define OTC_AMALGAMATION 1
#include "opentideconstants.h"
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(C / "dist"))
    a = ap.parse_args()
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    header = (C / "include/opentideconstants.h").read_text()
    version = re.search(r'#define OTC_VERSION "([^"]+)"', header).group(1)
    cjson = re.search(r"#define CJSON_VERSION_MAJOR (\d+)\s+#define CJSON_VERSION_MINOR (\d+)\s+#define CJSON_VERSION_PATCH (\d+)",
                      (C / "vendor/cjson/cJSON.h").read_text())
    chunks = [PRELUDE.format(version=version, cjson=".".join(cjson.groups()))]
    for part in PARTS:
        lines = []
        for line in (C / part).read_text().splitlines():
            m = LOCAL_INCLUDE.match(line)
            if m:
                lines.append(f"/* #include \"{m.group(1)}\" (inlined) */")
            else:
                lines.append(line)
        chunks.append(f"\n/* ======================================== {part} */\n" + "\n".join(lines) + "\n")
    (out / "opentideconstants.c").write_text("".join(chunks))
    (out / "opentideconstants.h").write_text(header)
    print(f"wrote {out / 'opentideconstants.c'} and {out / 'opentideconstants.h'}")


if __name__ == "__main__":
    main()
