# /// script
# requires-python = ">=3.10"
# ///
"""Generate the C library's derived sources (run from the repository root):

    uv run c/tools/gen_sources.py           write the files
    uv run c/tools/gen_sources.py --check   exit 1 if a committed file differs

- c/src/otc_cjson_rename.h: renames every public cJSON symbol to otc__cJSON_*,
  so an application can link its own cJSON next to this library.
- c/src/otc_sha256_rename.h: the same for the vendored SHA-256.
- c/src/otc_fold_table.c: conformance/name_fold.json as a sorted C table
  (SDK spec 4.4.1).
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
C = ROOT / "c"


def rename_header(guard, names, source):
    lines = [f"/* Generated by c/tools/gen_sources.py from {source}; do not edit. */",
             f"#ifndef {guard}", f"#define {guard}"]
    lines += [f"#define {n} otc__{n}" for n in names]
    lines += [f"#endif /* {guard} */", ""]
    return "\n".join(lines)


def cjson_names():
    text = (C / "vendor/cjson/cJSON.h").read_text()
    names = re.findall(r"CJSON_PUBLIC\([^)]*\)\s*([A-Za-z_][A-Za-z0-9_]*)\s*\(", text)
    # cJSON.c also has external functions that cJSON.h does not declare (cJSON_Duplicate_rec)
    source = (C / "vendor/cjson/cJSON.c").read_text()
    names += re.findall(r"^(?!static)[A-Za-z][^\n(;#]*?\b(cJSON_[A-Za-z0-9_]+)\s*\(", source, re.M)
    return sorted(set(n for n in names if n.startswith("cJSON_")))


def sha_names():
    text = (C / "vendor/sha256/sha-256.h").read_text()
    names = re.findall(r"^\s*(?:void|uint8_t \*)\s*([a-z_0-9]+)\s*\(", text, re.M)
    return sorted(set(names))


def c_escape(s):
    out = []
    for b in s.encode("utf-8"):
        if 0x20 <= b < 0x7F and b not in (0x22, 0x5C, 0x3F):
            out.append(chr(b))
        else:
            out.append(f"\\{b:03o}")
    return "".join(out)


def fold_table():
    doc = json.loads((ROOT / "conformance/name_fold.json").read_text(encoding="utf-8"))
    rows = sorted((int(k, 16), v) for k, v in doc["map"].items())
    lines = ["/* Generated by c/tools/gen_sources.py from conformance/name_fold.json", 
             f" * (Unicode {doc['unicode_version']}); do not edit. SDK spec 4.4.1. */",
             '#include "otc_internal.h"', "",
             "const otc_fold_entry otc__fold_table[] = {"]
    lines += [f'    {{0x{cp:04X}u, "{c_escape(v)}"}},' for cp, v in rows]
    lines += ["};", f"const size_t otc__fold_table_size = {len(rows)};", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    files = {
        C / "src/otc_cjson_rename.h": rename_header("OTC_CJSON_RENAME_H", cjson_names(), "c/vendor/cjson/cJSON.h"),
        C / "src/otc_sha256_rename.h": rename_header("OTC_SHA256_RENAME_H", sha_names(), "c/vendor/sha256/sha-256.h"),
        C / "src/otc_fold_table.c": fold_table(),
    }
    bad = 0
    for path, text in files.items():
        if a.check:
            if not path.exists() or path.read_text() != text:
                print(f"out of date: {path.relative_to(ROOT)}")
                bad = 1
        else:
            path.write_text(text)
    return bad


if __name__ == "__main__":
    sys.exit(main())
