/* Generated by c/tools/gen_sources.py from c/vendor/sha256/sha-256.h; do not edit. */
#ifndef OTC_SHA256_RENAME_H
#define OTC_SHA256_RENAME_H
#define calc_sha_256 otc__calc_sha_256
#define sha_256_close otc__sha_256_close
#define sha_256_init otc__sha_256_init
#define sha_256_write otc__sha_256_write
#endif /* OTC_SHA256_RENAME_H */
